<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EditorConfig.Core\EditorConfig.Core.csproj" />
		<PackageReference Include="TUnit" Version="1.65.51" />
		<PackageReference Include="AwesomeAssertions" Version="9.6.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="*\*.editorconfig">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="StopAtRoot\X\*.editorconfig">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="StopAtRoot\X\Y\Z\*.editorconfig">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="StopAtRoot\X\Y\*.editorconfig">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="CTestReproduce\unset\unset.editorconfig">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
