// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("EditorConfig.Tests")]
[assembly: AssemblyCopyrightAttribute("editorconfig.org 2015")]
[assembly: AssemblyDescriptionAttribute("EditorConfig.Tests")]
[assembly: AssemblyCompanyAttribute("EditorConfig")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.12.1")]
[assembly: AssemblyInformationalVersionAttribute("0.12.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.0";
    }
}
