// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("EditorConfig.Core")]
[assembly: AssemblyCopyrightAttribute("editorconfig.org 2014")]
[assembly: AssemblyDescriptionAttribute("A .NET implementation of the core editorconfig library")]
[assembly: AssemblyCompanyAttribute("EditorConfig")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.12.0")]
[assembly: AssemblyInformationalVersionAttribute("0.12.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.0";
    }
}
