// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("editorconfig.org 2015")]
[assembly: AssemblyDescriptionAttribute("A .NET implementation of the core editorconfig library")]

namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.0";
    }
}
